services:
  database:
    image: mysql:latest
    container_name: isdatabase
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: IS_database
      MYSQL_USER: user
      MYSQL_PASSWORD: ispass
    ports:
      - "3306:3306"
  backend:
    image: isbackend
    container_name: isbackend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: isdatabase
      DATABASE_PORT: 3306
      DATABASE_NAME: IS_database
      DATABASE_USER: user
      DATABASE_PASSWORD: ispass
  frontend:
    image: isfrontend
    container_name: isfrontend
    ports:
      - "5173:80"
    depends_on:
      - backend