apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: is-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzcw==       # "pass" base64 encoded
  MYSQL_DATABASE: SVNfZGF0YWJhc2U=   # "IS_database" base64 encoded
  MYSQL_USER: dXNlcg==               # "user" base64 encoded
  MYSQL_PASSWORD: aXNwYXNz           # "ispass" base64 encoded
